"""rename field mcp_server_configuration_ids

Revision ID: 6e960597029b
Revises: 5896119a5994
Create Date: 2025-08-26 13:09:43.509860+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e960597029b'
down_revision: Union[str, None] = '5896119a5994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server_bundles', sa.Column('mcp_server_configuration_ids', sa.ARRAY(sa.UUID()), nullable=False))
    op.drop_column('mcp_server_bundles', 'mcp_server_configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server_bundles', sa.Column('mcp_server_configurations', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.drop_column('mcp_server_bundles', 'mcp_server_configuration_ids')
    # ### end Alembic commands ###
