"""adding updated_at and changed hash type in user_refresh_tokens

Revision ID: 5896119a5994
Revises: acd24944d335
Create Date: 2025-08-26 09:47:53.955489+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5896119a5994'
down_revision: Union[str, None] = 'acd24944d335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_refresh_tokens', 'token_hash',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_refresh_tokens', 'token_hash',
               existing_type=sa.String(length=512),
               type_=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('user_refresh_tokens', 'updated_at')
    # ### end Alembic commands ###
