"""supported custom mcp server and added ops-account table

Revision ID: 967410def57b
Revises: 7b83f4be0060
Create Date: 2025-09-17 12:44:52.366446+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '967410def57b'
down_revision: Union[str, None] = '7b83f4be0060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('auth_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcp_server_id', name='uc_ops_account_mcp_server')
    )
    op.add_column('mcp_servers', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('mcp_servers', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_mcp_servers_organization_id', 'mcp_servers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mcp_servers_organization_id', 'mcp_servers', type_='foreignkey')
    op.drop_column('mcp_servers', 'last_synced_at')
    op.drop_column('mcp_servers', 'organization_id')
    op.drop_table('ops_accounts')
    # ### end Alembic commands ###
