"""add name and description to MCPServerConfiguration

Revision ID: 63224673a97a
Revises: 7ace8fa6021e
Create Date: 2025-09-01 22:12:16.288119+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63224673a97a'
down_revision: Union[str, None] = '7ace8fa6021e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server_configurations', sa.Column('name', sa.String(length=512), nullable=False))
    op.add_column('mcp_server_configurations', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server_configurations', 'description')
    op.drop_column('mcp_server_configurations', 'name')
    # ### end Alembic commands ###
