"""create unique index for shared accounts

Revision ID: b1d18d85aa49
Revises: a8253e7a0326
Create Date: 2025-09-22 17:31:13.074022+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d18d85aa49'
down_revision: Union[str, None] = 'a8253e7a0326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_operational_connected_accounts_one_per_mcp_server_config', 'connected_accounts', ['mcp_server_configuration_id'], unique=True, postgresql_where=sa.text("ownership = 'OPERATIONAL'"))
    op.create_index('ux_shared_connected_accounts_one_per_mcp_server_config', 'connected_accounts', ['mcp_server_configuration_id'], unique=True, postgresql_where=sa.text("ownership = 'SHARED'"))
    op.create_index('ux_mcp_server_config_per_server_org', 'mcp_server_configurations', ['mcp_server_id'], unique=True, postgresql_where=sa.text("connected_account_ownership = 'OPERATIONAL'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_mcp_server_config_per_server_org', table_name='mcp_server_configurations', postgresql_where=sa.text("connected_account_ownership = 'OPERATIONAL'"))
    op.drop_index('ux_shared_connected_accounts_one_per_mcp_server_config', table_name='connected_accounts', postgresql_where=sa.text("ownership = 'SHARED'"))
    op.drop_index('ux_operational_connected_accounts_one_per_mcp_server_config', table_name='connected_accounts', postgresql_where=sa.text("ownership = 'OPERATIONAL'"))
    # ### end Alembic commands ###
