"""add transport_type to MCPServer

Revision ID: 7ace8fa6021e
Revises: 6e960597029b
Create Date: 2025-08-31 19:57:02.769530+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ace8fa6021e'
down_revision: Union[str, None] = '6e960597029b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('transport_type', sa.Enum('STREAMABLE_HTTP', 'SSE', name='mcpservertransporttype', native_enum=False, length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'transport_type')
    # ### end Alembic commands ###
