"""add ownership to connected account

Revision ID: 7b83f4be0060
Revises: 63224673a97a
Create Date: 2025-09-11 10:40:19.113650+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b83f4be0060'
down_revision: Union[str, None] = '63224673a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('ownership', sa.Enum('INDIVIDUAL', 'SHARED', name='connectedaccountownership', native_enum=False, length=50), nullable=False, server_default='INDIVIDUAL'))
    op.add_column('mcp_server_configurations', sa.Column('connected_account_ownership', sa.Enum('INDIVIDUAL', 'SHARED', name='connectedaccountownership', native_enum=False, length=50), nullable=False, server_default='INDIVIDUAL'))
    # ### end Alembic commands ###

    # Remove default values
    op.alter_column('connected_accounts', 'ownership', server_default=None)
    op.alter_column('mcp_server_configurations', 'connected_account_ownership', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server_configurations', 'connected_account_ownership')
    op.drop_column('connected_accounts', 'ownership')
    # ### end Alembic commands ###
